mkLogFile : mkdirLog mkrestart.txt mkSwInfo mkProject

mkdirLog :
	mkdir -p log

mkrestart.txt :
	touch log/restart.txt

mkSwInfo :
	touch SwInfo.txt

mkProject :
	touch project.c

clean :
	rm -rf log
